---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ctf
  creationTimestamp: null
  labels:
    ctf: challenge
    app: had-a-bad-day
  name: had-a-bad-day
spec:
  replicas: 1
  selector:
    matchLabels:
      app: had-a-bad-day
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: had-a-bad-day
        ctf: challenge
    spec:
      containers:
      - image: rdctf/ctfd-had-a-bad-day
        name: had-a-bad-day
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      automountServiceAccountToken: false
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: ctf
  creationTimestamp: null
  labels:
    app: had-a-bad-day
  name: had-a-bad-day
spec:
  ports:
  - name: had-a-bad-day-web
    port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: had-a-bad-day
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: had-a-bad-day
  creationTimestamp: null
  namespace: ctf
  labels:
    app: had-a-bad-day
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`had-a-bad-day.ctf.rd-security-training.bbctest01.uk`)
      kind: Rule
      services:
        - name: had-a-bad-day
          namespace: ctf
          kind: Service
          port: 8000
  tls:
    # Specifying domains here adds the Host header to request to pod
    domains:
      - main: had-a-bad-day.ctf.rd-security-training.bbctest01.uk
    secretName: traefik-ctf-cert
