apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ctfd
  creationTimestamp: null
  name: ctfd-oauth2-proxy
  labels:
    ctfd: oauth2-proxy
    app: ctfd-oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctfd-oauth2-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        ctfd: oauth2-proxy
        app: ctfd-oauth2-proxy
    spec:
      containers:
      - args:
        - --provider
        - oidc
        - --oidc-issuer-url
        - https://sso-nbe.bbcis.uk/auth/realms/rd-security-training
        - --client-id
        - ctfd
        - --client-secret
        - $(client_secret)
        - --http-address
        - :8080
        - --upstream
        - http://ctfd-nginx:8080
        - --cookie-secure
        - "true"
        - --email-domain
        - "*"
        - --cookie-secret
        - $(cookie_secret)
        - --skip-provider-button
        - "true"
        env:
        - name: client_secret
          valueFrom:
            secretKeyRef:
              name: ctfd-oauth2-client-secret
              key: ctfd-oauth2-client-secret.txt
        - name: cookie_secret
          valueFrom:
            secretKeyRef:
              name: ctfd-oauth2-cookie-secret
              key: ctfd-oauth2-cookie-secret.txt
        image: quay.io/oauth2-proxy/oauth2-proxy
        imagePullPolicy: ""
        name: oauth2-proxy
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      automountServiceAccountToken: false
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: ctfd
  creationTimestamp: null
  labels:
    app: ctfd-oauth2-proxy
  name: ctfd-oauth2-proxy
spec:
  ports:
  - name: ui
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ctfd-oauth2-proxy
  type: ClusterIP
status: {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ctfd-secure
  creationTimestamp: null
  namespace: ctfd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ctfd.rd-security-training.bbctest01.uk`)
      kind: Rule
      services:
        - name: ctfd-oauth2-proxy
          namespace: ctfd
          kind: Service
          port: 8080
  tls: {}
