apiVersion: v1
kind: ConfigMap
metadata:
  name: legion-of-doom-html
  namespace: ctf
data:
  index.html: |
    <html>
    <head>
      <title>Legion Of Doom</title>
    </head>
    <body>
      <h1>Legion Of Doom</h1>
      <p>You found us! You may join our legion. See the below links to join us</p>
      <p style="color:white">Flag is: CTF{security_through_obscurity_isnt_valid}</p>
      <p>Website: <a href="https://www.youtube.com/watch?v=TMNeSnjZfCI">Here</a></p>
      <p>Twitter: <a href="https://www.youtube.com/watch?v=TMNeSnjZfCI">Here</a></p>
      <p>Facebook: <a href="https://www.youtube.com/watch?v=TMNeSnjZfCI">Here</a></p>
      <p>Youtube: <a href="https://www.youtube.com/watch?v=TMNeSnjZfCI">Here</a></p>

      <p>P.S. <a href="https://www.youtube.com/watch?v=TMNeSnjZfCI">See "DEF CON 25 - Hanno Bõck - Abusing Certificate Transparency Logs" on youtube</a></p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ctf
  creationTimestamp: null
  labels:
    ctf: challenge
    app: legion-of-doom
  name: legion-of-doom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legion-of-doom
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: legion-of-doom
        ctf: challenge
    spec:
      containers:
      - image: nginx:1.17
        imagePullPolicy: ""
        name: legion-of-doom
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          readOnly: true
          name: legion-of-doom-html
      restartPolicy: Always
      serviceAccountName: ""
      automountServiceAccountToken: false
      volumes:
      - name: legion-of-doom-html
        configMap:
          name: legion-of-doom-html
          items:
            - key: index.html
              path: index.html
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: ctf
  creationTimestamp: null
  labels:
    app: legion-of-doom
  name: legion-of-doom
spec:
  ports:
  - name: legion-of-doom-web
    port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: legion-of-doom
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: legion-of-doom
  creationTimestamp: null
  namespace: ctf
  labels:
    app: legion-of-doom
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`legion-of-doom-127483634.ctf.rd-security-training.bbctest01.uk`)
      kind: Rule
      services:
        - name: legion-of-doom
          namespace: ctf
          kind: Service
          port: 8000
  tls:
    # Specifying domains here adds the Host header to request to pod
    domains:
      - main: legion-of-doom-127483634.ctf.rd-security-training.bbctest01.uk
    secretName: traefik-ctf-cert
