---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ctf
  creationTimestamp: null
  labels:
    ctf: challenge
    app: hurdles
  name: hurdles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hurdles
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hurdles
        ctf: challenge
    spec:
      containers:
      - image: localhost:32000/ctf-hurdles:registry
        name: hurdles
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      automountServiceAccountToken: false
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: ctf
  creationTimestamp: null
  labels:
    app: hurdles
  name: hurdles
spec:
  ports:
  - name: hurdles-web
    port: 8000
    protocol: TCP
    targetPort: 8888
  selector:
    app: hurdles
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: add-xforwarded-headers
  namespace: ctf
spec:
  headers:
    customRequestHeaders:
      x-forwarded-for: '13.37.13.37, 127.0.0.1'
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hurdles
  creationTimestamp: null
  namespace: ctf
  labels:
    app: hurdles
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hurdles.ctf.rd-security-training.bbctest01.uk`)
      kind: Rule
      services:
        - name: hurdles
          namespace: ctf
          kind: Service
          port: 8000
      middlewares:
        - name: add-xforwarded-headers
          namespace: ctf
  tls:
    # Specifying domains here adds the Host header to request to pod
    domains:
      - main: hurdles.ctf.rd-security-training.bbctest01.uk
    secretName: traefik-ctf-cert
